#backgrounds
image darkcyberbg = "networkbgdark.png"
image networkinventorybg = "networkinventory.png"
image commonsystemsbg = "commonsystems.png" 
image powershellbg = "powerShellIntro.png"

image systemWinEvent = "systemeventlogs.png"
image systemSecurityEvent = "securityeventlogs.png"
image systemMiscLog = "miscellaneousEventLogs.png"

image psgetprocess = "psgetprocess.png"
image psgetservice = "psgetservice.png"
image psgetpackage = "psgetpackage.png"
image psgetlocaluser = "psgetlocaluser.png"
image psgeteventcode = "psgeteventlog.png"
image psgeteventcodeoutputgridview = "psgeteventlogoutgridview.png"

image sopcap1 = "sopcap1.png"
image sopcap2 = "sopcap2.png"
image sopcap3 = "sopcap3.png"
image sopcap4 = "sopcap4.png"
image soalerts = "soalerts.png"
image sodashboards = "sodashboards.png"
image sohunt = "sohunt.png"

image gravwelldashboards = "gravwelldashboard.png"
image gravwellkits = "gravwellkits.png"
image gravwelloverview = "gravwelloverview.png"
image gravwellsearch = "gravwellsearch.png"

image pfsense_main = "pfsense_main.png"
image pfsense_main1 = "pfsense_main1.png"
image pfsense_main2 = "pfsense_main2.png"
image pfsense_main3 = "pfsense_main3.png"
image pfsense_main4 = "pfsense_main4.png"
image pfsense_main5 = "pfsense_main5.png"
image pfsense_main6 = "pfsense_main6.png"
image pfsense_main7 = "pfsense_main7.png"

image narrator sensai = "sensai.png"
